version: '3'

services:
  localmovie-web:
    image: 192.168.1.8:5000/localmovie-web:latest
    ports:
      - "8080:8080"
    volumes:
    - "/media/nathan/LocalMedia:/media/nathan/LocalMedia"
  localmovie-media-manager:
    image: 192.168.1.8:5000/localmovie-media-manager:latest
    ports:
      - "8081:8081"
    volumes:
      - "/media/nathan/LocalMedia:/media/nathan/LocalMedia"
  redis:
    image: library/redis:alpine
#  keycloak:
#    image: jboss/keycloak
#    ports:
#      - "8082:8080"
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: pw123
#      DB_VENDOR: h2
#      DB_USER: keycloak
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: pw123
      POSTGRES_USER: localmovies